public class fenetre_accueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fenetre_accueil.class.getName());

    /**
     * Creates new form fenetre_accueil
     */
    public fenetre_accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_titre = new javax.swing.JLabel();
        texte_phrase = new javax.swing.JLabel();
        slider_tentatives = new javax.swing.JSlider();
        bouton_lancer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_titre.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        texte_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_titre.setText("TROUVER LE CODE");
        getContentPane().add(texte_titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 400, 80));

        texte_phrase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        texte_phrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_phrase.setText("Choisissez le nombre de tentatives");
        getContentPane().add(texte_phrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 400, 50));

        slider_tentatives.setMajorTickSpacing(2);
        slider_tentatives.setMaximum(15);
        slider_tentatives.setMinimum(1);
        slider_tentatives.setPaintLabels(true);
        slider_tentatives.setValue(8);
        slider_tentatives.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_tentativesStateChanged(evt);
            }
        });
        getContentPane().add(slider_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 530, 60));

        bouton_lancer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bouton_lancer.setText("LANCER");
        bouton_lancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_lancerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_lancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slider_tentativesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_tentativesStateChanged

    }//GEN-LAST:event_slider_tentativesStateChanged

    private void bouton_lancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_lancerActionPerformed
    int nbTentatives = slider_tentatives.getValue();

    // Créer la fenêtre du jeu avec ce nombre de tentatives
    fenetre_cadenas fen = new fenetre_cadenas(nbTentatives);
    fen.setLocationRelativeTo(null); // centre la fenêtre à l'écran
    fen.setVisible(true);

    // Fermer la fenêtre d'accueil
    this.dispose();
    }//GEN-LAST:event_bouton_lancerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fenetre_accueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_lancer;
    private javax.swing.JSlider slider_tentatives;
    private javax.swing.JLabel texte_phrase;
    private javax.swing.JLabel texte_titre;
    // End of variables declaration//GEN-END:variables
}
