/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jacqu
 */
public class fenetre_cadenas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fenetre_cadenas.class.getName());

    /**
     * Creates new form fenetre_cadenas
     */
    public fenetre_cadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Trouvez le bon code en moins de 5 tentatives :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 22, 370, 40));

        jToggleButton1.setText("/\\");
            jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jToggleButton1ActionPerformed(evt);
                }
            });
            getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 60, 30));

            jToggleButton2.setText("/\\");
                jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jToggleButton2ActionPerformed(evt);
                    }
                });
                getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, 30));

                jToggleButton3.setText("/\\");
                    jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 60, 30));

                    jToggleButton4.setText("\\/");
                    jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    getContentPane().add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 60, 30));

                    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                    jLabel2.setText("0");
                    jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 40, 85));

                    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                    jLabel3.setText("0");
                    jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 40, 85));

                    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                    jLabel4.setText("0");
                    jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 40, 85));

                    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                    jLabel5.setText("0");
                    jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 40, 85));

                    jToggleButton5.setText("/\\");
                        jToggleButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        getContentPane().add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 30));

                        jToggleButton6.setText("\\/");
                        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jToggleButton6ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, 30));

                        jToggleButton7.setText("\\/");
                        jToggleButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        getContentPane().add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 60, 30));

                        jToggleButton8.setText("\\/");
                        jToggleButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        getContentPane().add(jToggleButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 60, 30));

                        jToggleButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                        jToggleButton9.setText("TESTER");
                        getContentPane().add(jToggleButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 120, 40));

                        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                        jLabel6.setText("Nombre de chiffres trop bas :");
                        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 230, 30));

                        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                        jLabel7.setText("Nombre de chiffres exactes :");
                        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, 30));

                        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                        jLabel8.setText("Nombre de chiffres trop hauts :");
                        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 230, 30));

                        jLabel9.setText("jLabel9");
                        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 60, 20));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fenetre_cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
