public class fenetre_accueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fenetre_accueil.class.getName());

    /**
     * Creates new form fenetre_accueil
     */
    public fenetre_accueil() {
        initComponents();
    this.setSize(600, 500);
    this.setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_titre = new javax.swing.JLabel();
        texte_phrase = new javax.swing.JLabel();
        slider_tentatives = new javax.swing.JSlider();
        bouton_lancer = new javax.swing.JButton();
        image_cadenas_1 = new javax.swing.JLabel();
        image_cadenas_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texte_titre.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        texte_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_titre.setText("TROUVER LE CODE");

        texte_phrase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        texte_phrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_phrase.setText("Choisissez le nombre de tentatives");

        slider_tentatives.setMajorTickSpacing(2);
        slider_tentatives.setMaximum(15);
        slider_tentatives.setMinimum(1);
        slider_tentatives.setPaintLabels(true);
        slider_tentatives.setValue(8);
        slider_tentatives.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_tentativesStateChanged(evt);
            }
        });

        bouton_lancer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bouton_lancer.setText("LANCER");
        bouton_lancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_lancerActionPerformed(evt);
            }
        });

        image_cadenas_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image cadenas.png"))); // NOI18N
        image_cadenas_1.setText("jLabel1");
        image_cadenas_1.setToolTipText("");

        image_cadenas_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image cadenas.png"))); // NOI18N
        image_cadenas_2.setText("jLabel1");
        image_cadenas_2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texte_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texte_phrase, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(image_cadenas_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(bouton_lancer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(image_cadenas_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(slider_tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(texte_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(texte_phrase, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(slider_tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(image_cadenas_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image_cadenas_2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bouton_lancer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slider_tentativesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_tentativesStateChanged

    }//GEN-LAST:event_slider_tentativesStateChanged

    private void bouton_lancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_lancerActionPerformed
    int nbTentatives = slider_tentatives.getValue();

    // Créer la fenêtre du jeu avec ce nombre de tentatives
    fenetre_cadenas fen = new fenetre_cadenas(nbTentatives);
    fen.setLocationRelativeTo(null); // centre la fenêtre à l'écran
    fen.setVisible(true);

    // Fermer la fenêtre d'accueil
    this.dispose();
    }//GEN-LAST:event_bouton_lancerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fenetre_accueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_lancer;
    private javax.swing.JLabel image_cadenas_1;
    private javax.swing.JLabel image_cadenas_2;
    private javax.swing.JSlider slider_tentatives;
    private javax.swing.JLabel texte_phrase;
    private javax.swing.JLabel texte_titre;
    // End of variables declaration//GEN-END:variables
}
