public class fenetre_cadenas extends javax.swing.JFrame {
    
    private JeuCadenas jeu;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fenetre_cadenas.class.getName());

public fenetre_cadenas() {
    initComponents();
    jeu = new JeuCadenas(); // ⭐ moteur du jeu
    resetAffichage();       // ⭐ affiche tout à zéro au lancement
}

private void resetAffichage() {

    // Réinitialiser les 4 chiffres affichés à 0
    texte_chiffre_1.setText("0");
    texte_chiffre_2.setText("0");
    texte_chiffre_3.setText("0");
    texte_chiffre_4.setText("0");

    // Réinitialiser les compteurs
    texte_nb_chiffres_exacts.setText("0");
    texte_nb_chiffres_haut.setText("0");
    texte_nb_chiffres_bas.setText("0");

    // "0 sur 5" (ou 0 sur maxTentatives)
    texte_score.setText("0 sur " + jeu.getMaxTentatives());

    // Enlever message perdu/gagné
    texte_perdu.setText("");

    // Réactiver le bouton Tester
    bouton_tester.setEnabled(true);
    
    texte_intro.setText("Trouvez le bon code en moins de " 
                    + jeu.getMaxTentatives() + " tentative(s) :");

}


// Lit le chiffre affiché dans un JLabel (0 à 9)
private int lireChiffre(javax.swing.JLabel label) {
    return Integer.parseInt(label.getText());
}

// Met à jour le JLabel avec une nouvelle valeur (0 à 9)
private void setChiffre(javax.swing.JLabel label, int valeur) {
    if (valeur < 0) {
        valeur = 0;
    }
    if (valeur > 9) {
        valeur = 9;
    }
    label.setText(Integer.toString(valeur));
}

// Construit un objet Code à partir des 4 labels de chiffres
private Code lireCodePropose() {
    int c1 = lireChiffre(texte_chiffre_1);
    int c2 = lireChiffre(texte_chiffre_2);
    int c3 = lireChiffre(texte_chiffre_3);
    int c4 = lireChiffre(texte_chiffre_4);
    return new Code(c1, c2, c3, c4);
}

private void mettreAJourTexteIntro() {
    int faites = jeu.getNbTentatives();
    int max = jeu.getMaxTentatives();
    int restantes = max - faites;

    if (!jeu.isTermine()) {
        texte_intro.setText("Trouvez le bon code en moins de " +restantes+" tentative(s) :");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        texte_chiffre_4 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_lbl__nb_chiffres_bas = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        bouton_recommencer = new javax.swing.JButton();
        texte_perdu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texte_intro.setText("Trouvez le bon code en moins de 5 tentatives :");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 22, 370, 40));

        texte_chiffre_4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        texte_chiffre_4.setText("0");
        texte_chiffre_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 40, 85));

        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        texte_chiffre_1.setText("0");
        texte_chiffre_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 40, 85));

        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        texte_chiffre_2.setText("0");
        texte_chiffre_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 40, 85));

        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        texte_chiffre_3.setText("0");
        texte_chiffre_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 40, 85));

        texte_lbl__nb_chiffres_bas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texte_lbl__nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
        getContentPane().add(texte_lbl__nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 230, 30));

        texte_lbl_nb_chiffres_exacts.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exactes :");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, 30));

        texte_lbl_nb_chiffres_haut.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop hauts :");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 230, 30));

        texte_nb_chiffres_bas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texte_nb_chiffres_bas.setText("0");
        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 30, 30));

        texte_nb_chiffres_exacts.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texte_nb_chiffres_exacts.setText("0");
        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 30, 30));

        texte_nb_chiffres_haut.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texte_nb_chiffres_haut.setText("0");
        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 30, 30));

        texte_tentatives.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        texte_tentatives.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_tentatives.setText("Tentatives :");
        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 110, 30));

        texte_score.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        texte_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_score.setText("0 sur 5");
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 110, 80));

        up_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 30));

            up_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 60, 30));

                up_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, 30));

                    up_chiffre_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 60, 30));

                        down_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, 30));

                        down_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 60, 30));

                        down_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 60, 30));

                        down_chiffre_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 60, 30));

                        bouton_tester.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                        bouton_tester.setText("TESTER");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 120, 40));

                        bouton_recommencer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                        bouton_recommencer.setText("RECOMMENCER");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 190, 40));

                        texte_perdu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                        texte_perdu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_perdu.setText("perdu ou gagné");
                        getContentPane().add(texte_perdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 60));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
    // On relance une nouvelle partie côté logique
    jeu.recommencer();

    // On remet l'affichage à zéro
    resetAffichage();
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
    int val = lireChiffre(texte_chiffre_1);
    if (val < 9) {
        val++;
    }
    setChiffre(texte_chiffre_1, val); 
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
    int val = lireChiffre(texte_chiffre_2);
    if (val < 9) {
        val++;
    }
    setChiffre(texte_chiffre_2, val);
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
    int val = lireChiffre(texte_chiffre_3);
    if (val < 9) {
        val++;
    }
    setChiffre(texte_chiffre_3, val);
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
    int val = lireChiffre(texte_chiffre_4);
    if (val < 9) {
        val++;
    }
    setChiffre(texte_chiffre_4, val);
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
    int val = lireChiffre(texte_chiffre_1);
    if (val > 0) {
        val--;
    }
    setChiffre(texte_chiffre_1, val);
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
    int val = lireChiffre(texte_chiffre_2);
    if (val > 0) {
        val--;
    }
    setChiffre(texte_chiffre_2, val);
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
    int val = lireChiffre(texte_chiffre_3);
    if (val > 0) {
        val--;
    }
    setChiffre(texte_chiffre_3, val);
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
    int val = lireChiffre(texte_chiffre_4);
    if (val > 0) {
        val--;
    }
    setChiffre(texte_chiffre_4, val);
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
    // On efface l’ancien message temporairement
    texte_perdu.setText("");

    // 1) Lire le code proposé par le joueur
    Code proposition = lireCodePropose();

    // 2) Demander au moteur du jeu de tester la combinaison
    ResultatEssai res = jeu.testerCombinaison(proposition);

    // 3) Afficher les résultats dans les labels
    texte_nb_chiffres_exacts.setText(
            Integer.toString(res.getNbChiffresExacts()));
    texte_nb_chiffres_haut.setText(
            Integer.toString(res.getNbChiffresTropHauts()));
    texte_nb_chiffres_bas.setText(
            Integer.toString(res.getNbChiffresTropBas()));

    // Mettre à jour "X sur 5"
    texte_score.setText(jeu.getNbTentatives()
            + " sur " + jeu.getMaxTentatives());

    mettreAJourTexteIntro();

    // 4) Gérer les messages gagné / perdu / réessayer
    if (res.isGagne()) {
        texte_perdu.setText("Gagné !");
        bouton_tester.setEnabled(false);      // on bloque le jeu
    } else if (jeu.isTermine()) {
        // Pas gagné, mais plus de tentatives = perdu
        texte_perdu.setText("Perdu... nombre d'essais atteint.");
        bouton_tester.setEnabled(false);
    } else {
        // Pas encore fini, on invite à réessayer
        texte_perdu.setText("Perdu, réessayez !");
    }

    }//GEN-LAST:event_bouton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fenetre_cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_chiffre_4;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl__nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_perdu;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
